[package]
name = "verifgsigma"
version = "1.4.9"
edition = "2021"




[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.5", features = ["cors", "trace"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "mysql"] }
rust-embed = "8.4"
mime_guess = "2.0"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"

reqwest = { version = "0.11", features = ["json"] }
sha2 = "0.10"
hex = "0.4"
windows-sys = { version = "0.52", features = ["Win32_UI_Shell", "Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_Graphics_Gdi", "Win32_System_LibraryLoader"] }

[build-dependencies]
winres = "0.1"


